localserver: add regression test for closed channel panic
```
--- FAIL: Test_sendCallback_close (0.00s)
panic: send on closed channel [recovered, repanicked]

goroutine 21 [running]:
testing.tRunner.func1.2({0xcc2b00, 0xe3be60})
        /home/billy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.5.linux-amd64/src/testing/testing.go:1974 +0x232
testing.tRunner.func1()
        /home/billy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.5.linux-amd64/src/testing/testing.go:1977 +0x349
panic({0xcc2b00?, 0xe3be60?})
        /home/billy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.5.linux-amd64/src/runtime/panic.go:860 +0x13a
github.com/kolide/launcher/v2/ee/localserver.(*kryptoEcMiddleware).sendCallback(0x33e96c87040, 0x33e96c8a640, 0x0?)
        /home/billy/work/launcher/ee/localserver/krypto-ec-middleware.go:319 +0x371
github.com/kolide/launcher/v2/ee/localserver.Test_sendCallback_close(0x33e96c34d88)
        /home/billy/work/launcher/ee/localserver/krypto-ec-middleware_test.go:961 +0x23f
testing.tRunner(0x33e96c34d88, 0xe353d0)
        /home/billy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.5.linux-amd64/src/testing/testing.go:2036 +0xea
created by testing.(*T).Run in goroutine 1
        /home/billy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.5.linux-amd64/src/testing/testing.go:2101 +0x4c5
FAIL    github.com/kolide/launcher/v2/ee/localserver    0.007s
FAIL
```

This also happens with poor network connectivity during launcher
shutdown. Or in CI, when an in flight request races with cleanup and
middleware closure:

https://github.com/kolide/launcher/actions/runs/29709483013/job/88251553893

```
panic: send on closed channel

goroutine 234 [running]:
github.com/kolide/launcher/v2/ee/localserver.(*kryptoEcMiddleware).sendCallback(0xc0005b8820, 0xc000162140, 0xc0002a2540)
	D:/a/launcher/launcher/ee/localserver/krypto-ec-middleware.go:319 +0x67e
github.com/kolide/launcher/v2/ee/localserver.Test_sendCallback.func4()
	D:/a/launcher/launcher/ee/localserver/krypto-ec-middleware_test.go:749 +0x155
created by github.com/kolide/launcher/v2/ee/localserver.Test_sendCallback in goroutine 12
	D:/a/launcher/launcher/ee/localserver/krypto-ec-middleware_test.go:746 +0x7c5
FAIL	github.com/kolide/launcher/v2/ee/localserver	5.644s
```