pkg/osquery: fix flaky secretless enrollment test
I've seen two flakes.

The first is harder to hit, because a the window is tiny. If `GetQueries`
in `getQueriesWithReenroll` sees no nodeKey, it enters `Enroll`. If the
key is then set after entering `Enroll`, it checks the nodeKey and then
tries to store it. That causes this failure:
```
--- FAIL: TestGetQueries_WorksWithSecretlessEnrollment (60.10s)
    mock.go:361:
        assert: mock: I don't know what to return because the method call was unexpected.
        	Either do Mock.On("EnsureEnrollmentStored").Return(...) first, or remove the EnsureEnrollmentStored() call.
        	This method was unexpected:
        		EnsureEnrollmentStored(string)
        		0: "default"
        	at: [/home/runner/work/launcher/launcher/ee/agent/types/mocks/knapsack.go:1725 /home/runner/work/launcher/launcher/pkg/osquery/extension.go:344 /home/runner/work/launcher/launcher/pkg/osquery/extension.go:1051 /home/runner/work/launcher/launcher/pkg/osquery/extension.go:1026 /home/runner/work/launcher/launcher/pkg/osquery/extension_test.go:1692 /opt/hostedtoolcache/go/1.26.6/x64/src/runtime/asm_amd64.s:1771]
FAIL
coverage: 74.9% of statements
```

And this race when a GetQueries goroutine rarely grabs the node key _after_ Unset, but before we set the new mock.
```
goroutine 515 [running]:
github.com/kolide/launcher/v2/ee/agent/types/mocks.(*Knapsack).NodeKey(0xc0001cc230, {0x13865a3, 0x7})
        /home/billy/work/launcher/ee/agent/types/mocks/knapsack.go:3076 +0x338
github.com/kolide/launcher/v2/pkg/osquery.(*Extension).nodeKey(...)
        /home/billy/work/launcher/pkg/osquery/extension.go:520
github.com/kolide/launcher/v2/pkg/osquery.(*Extension).getQueriesWithReenroll(0xc0001aa180, {0x13e27f0, 0xc000280090}, 0x1)
        /home/billy/work/launcher/pkg/osquery/extension.go:1047 +0x189
github.com/kolide/launcher/v2/pkg/osquery.(*Extension).GetQueries(0xc0001aa180, {0x13e2828, 0xc0001cc1e0})
        /home/billy/work/launcher/pkg/osquery/extension.go:1026 +0x289
github.com/kolide/launcher/v2/pkg/osquery.TestGetQueries_WorksWithSecretlessEnrollment.func2()
        /home/billy/work/launcher/pkg/osquery/extension_test.go:1698 +0x71
created by github.com/kolide/launcher/v2/pkg/osquery.TestGetQueries_WorksWithSecretlessEnrollment in goroutine 514
        /home/billy/work/launcher/pkg/osquery/extension_test.go:1695 +0x8ff
FAIL    github.com/kolide/launcher/v2/pkg/osquery       23.531s
```